# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  before_all do
    setup_circle_ci
  end
end

lane :tests do
  run_tests(scheme: "SimpleProject", devices: ["iPhone SE (3rd generation)"], max_concurrent_simulators: 1, 
	concurrent_workers: 1,
	disable_concurrent_testing: true)
end

lane :fetch_screenshotbot do
    sh "curl https://cdn.screenshotbot.io/recorder.sh | sh"
end

lane :screenshotbot_upload_all do
  # For each __Snapshots__ directory, load it to screenshotbot
  Dir.glob("../**/__Snapshots__/").each do |dir|
    channel_name = dir[3..-("/__Snapshots__/".length + 1)]
    sh "~/screenshotbot/recorder --channel #{channel_name} --directory #{dir} --recursive"
  end
end

lane :screenshotbot_ci do
  tests
  fetch_screenshotbot
  screenshotbot_upload_all
end

